<?php

namespace Database\Factories;

use App\Models\Inquiry;
use App\Support\PhoneNumber;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Inquiry>
 */
class InquiryFactory extends Factory
{
    protected $model = Inquiry::class;

    public function definition(): array
    {
        return [
            // reference is auto-generated by the model's creating hook
            'status' => Inquiry::STATUS_NEW,
            'customer_name' => $this->faker->name(),
            'customer_mobile' => PhoneNumber::toE164('05'.$this->faker->numerify('01234567')),
            'is_whatsapp' => $this->faker->boolean(80),
            'customer_email' => $this->faker->optional()->safeEmail(),
            'customer_company' => $this->faker->optional()->company(),
            'customer_message' => $this->faker->optional()->sentence(),
            'currency' => 'AED',
            'locale' => $this->faker->randomElement(['en', 'ar']),
        ];
    }
}
